### ISSUE TITLE
Call to undefined function JQ() in libcalendaring_itip.php:552

### ISSUE THREAD

**Issue by EdemarSantos** [messagerie-melanie2/Roundcube-Plugin-Libcalendaring#1]
## I always have the fatal error above 
when I try to open an e-mail with calendar 
(test with e-mails generated by Cisco WebEx and Google Agenda):

Fatal error: Uncaught Error: Call to undefined function JQ() in /var/www/plugins/roundcube-plugins/plugins/libcalendaring/lib/libcalendaring_itip.php:552 
Stack trace: 
#0 /var/www/plugins/roundcube-plugins/plugins/calendar/calendar.php(3074): libcalendaring_itip->mail_itip_inline_ui(Array, 'accepted', '3:0', 'calendar', Object(DateTime), './?_task=calend...') 
#1 /var/www/program/lib/Roundcube/rcube_plugin_api.php(439): calendar->mail_messagebody_html(Array) 
#2 /var/www/program/include/rcmail_output_html.php(1214): rcube_plugin_api->exec_hook('template_object...', Array) 
#3 [internal function]: rcmail_output_html->xml_command(Array) 
#4 /var/www/program/include/rcmail_output_html.php(1022): preg_replace_callback('/<roundcube:([-...', Array, '<roundcube:obje...') 
#5 /var/www/program/include/rcmail_output_html.php(635): rcmail_output_html->parse_xml('<roundcube:obje...') 
#6 /var/www/program/include/rcmail_output_html.php(489): rcmail_output_html->parse('messagepreview', false) 
#7 /var/www/program/steps/mail/show.inc(162): rcma in /var/www/plugins/roundcube-plugins/plugins/libcalendaring/lib/libcalendaring_itip.php on line 552

## I'm using Roundcube Webmail 1.3-beta with plugins and versions:
acl 1.6
additional_message_headers 1.2.1
archive 3.0
attachment_position attachment_reminder 1.1
calendar 3.2.8
contextmenu 2.2.1
contextmenu_folder 1.2.47
filesystem_attachments 1.0
hide_blockquote 1.0
infinitescroll load
jqueryui 1.12.0
libcalendaring 3.2.8
markasjunk 1.2
message_highlight 
odfviewer 3.2.3
pdfviewer 3.2.5
piwik_analytics --
thunderbird_labels 
zipdownload 3.2

**Comment by EdemarSantos** [comment]
Hack to read the content of e-mail: use Reply or Forward!

**Comment by EdemarSantos** [comment]
In Google Agenda we have:
```
Content-Type: application/ics; name="invite.ics"
Content-Disposition: attachment; filename="invite.ics"
Content-Transfer-Encoding: base64
```
